services:
  rocland-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rocland-api
    ports:
      - "5000:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - C:\RoclandConfig\AccesoControlWeb.Secrets.json:C:\app\Modules\AccesoControlWeb\appsettings.Secrets.json:ro
      - C:\RoclandConfig\AccesoControlMobile.Secrets.json:C:\app\Modules\AccesoControlMobile\appsettings.Secrets.json:ro
    entrypoint: ["dotnet", "Rocland.Api.dll"]