services:
  rocland-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rocland-api
    ports:
      - "5000:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - C:\RoclandConfig\AccesoControlWeb:C:\app\Modules\AccesoControlWeb:ro
      - C:\RoclandConfig\AccesoControlMobile:C:\app\Modules\AccesoControlMobile:ro
    entrypoint: ["dotnet", "Rocland.Api.dll"]