services:
  rocland-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rocland-api
    ports:
      - "5000:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      # Mapeo de configuración externa (donde guardas tus appsettings.Secrets.json)
      - C:\RoclandConfig:C:\external_secrets:ro
    entrypoint: 
      - cmd
      - /c
      - copy C:\external_secrets\appsettings.Secrets.json C:\app\appsettings.Secrets.json && dotnet Rocland.Api.dll